# This workflow will build a Java project with Maven

name: Run SauceDemo UI Test Cases

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build and Run tests with Maven
      run: mvn clean test -DsuiteFile=testRunner/testng.xml